use std::collections::HashMap;
use std::fs;
use std::path::Path;

use anyhow::{Context, Result};

#[derive(Debug, Clone)]
pub struct OpsBucketConfig {
    pub domain: String,
    pub admin_email: String,
    pub admin_password: String,
    pub secret_key: String,
    pub postgres_password: String,
    pub clickhouse_password: String,
    pub minio_access_key: String,
    pub minio_secret_key: String,
    pub compose_project: String,
}

impl OpsBucketConfig {
    pub fn generate(password: &str, domain: &str, email: &str) -> Self {
        Self {
            domain: domain.to_string(),
            admin_email: email.to_string(),
            admin_password: password.to_string(),
            secret_key: format!("sk_{}", uuid_v4_short()),
            postgres_password: uuid_v4_short(),
            clickhouse_password: uuid_v4_short(),
            minio_access_key: uuid_v4_short(),
            minio_secret_key: uuid_v4_short(),
            compose_project: "opsbucket".into(),
        }
    }

    pub fn load(path: &Path) -> Result<Self> {
        let content = fs::read_to_string(path.join(".env")).context("failed to read .env file")?;

        let mut map = HashMap::new();
        for line in content.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            if let Some((key, value)) = line.split_once('=') {
                map.insert(key.trim().to_string(), value.trim().to_string());
            }
        }

        Ok(OpsBucketConfig {
            domain: map.get("DOMAIN").cloned().unwrap_or_default(),
            admin_email: map.get("ADMIN_EMAIL").cloned().unwrap_or_default(),
            admin_password: map.get("ADMIN_PASSWORD").cloned().unwrap_or_default(),
            secret_key: map.get("SECRET_KEY").cloned().unwrap_or_default(),
            postgres_password: map.get("POSTGRES_PASSWORD").cloned().unwrap_or_default(),
            clickhouse_password: map.get("CLICKHOUSE_PASSWORD").cloned().unwrap_or_default(),
            minio_access_key: map.get("MINIO_ACCESS_KEY").cloned().unwrap_or_default(),
            minio_secret_key: map.get("MINIO_SECRET_KEY").cloned().unwrap_or_default(),
            compose_project: map
                .get("COMPOSE_PROJECT")
                .cloned()
                .unwrap_or_else(|| "opsbucket".into()),
        })
    }

    pub fn save(&self, path: &Path) -> Result<()> {
        let content = format!(
            r#"# OpsBucket Configuration
# Generated by `opsbucket install`
COMPOSE_PROJECT={project}
DOMAIN={domain}
ADMIN_EMAIL={email}
ADMIN_PASSWORD={password}
SECRET_KEY={sk}
POSTGRES_PASSWORD={pgpass}
CLICKHOUSE_PASSWORD={chpass}
MINIO_ACCESS_KEY={minkey}
MINIO_SECRET_KEY={minsecret}
"#,
            project = self.compose_project,
            domain = self.domain,
            email = self.admin_email,
            password = self.admin_password,
            sk = self.secret_key,
            pgpass = self.postgres_password,
            chpass = self.clickhouse_password,
            minkey = self.minio_access_key,
            minsecret = self.minio_secret_key,
        );
        fs::write(path.join(".env"), content).context("failed to write .env file")?;
        Ok(())
    }

    #[allow(dead_code)]
    pub fn mask(&self) -> String {
        fn mask(s: &str) -> String {
            if s.len() > 8 {
                format!("{}***", &s[..4])
            } else {
                "***".into()
            }
        }
        format!(
            "Domain: {}\nEmail: {}\nAdmin Password: {}\nSecret Key: {}\nPostgres: {}",
            self.domain,
            self.admin_email,
            mask(&self.admin_password),
            mask(&self.secret_key),
            mask(&self.postgres_password),
        )
    }
}

fn uuid_v4_short() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    format!("{:x}", nanos)
}
