CREATE TABLE IF NOT EXISTS events (
    project_id String,
    message_id String,
    type String,
    anonymous_id String,
    user_id Nullable(String),
    resolved_user_id Nullable(String),
    event String,
    properties String,
    traits String,
    timestamp DateTime64(3),
    received_at DateTime64(3),
    original_timestamp DateTime64(3),
    context_page_url String,
    context_page_path String,
    context_page_referrer String,
    context_page_title String,
    context_page_search String,
    context_screen_width UInt16,
    context_screen_height UInt16,
    context_screen_density Float32,
    context_user_agent String,
    context_locale String,
    context_timezone String,
    context_campaign_source Nullable(String),
    context_campaign_medium Nullable(String),
    context_campaign_name Nullable(String),
    context_campaign_term Nullable(String),
    context_campaign_content Nullable(String),
    context_library_name String,
    context_library_version String,
    context_ip String
) ENGINE = MergeTree()
PARTITION BY toYYYYMM(timestamp)
ORDER BY (project_id, event, timestamp);
